<link href="{{asset('frontend')}}/css/plugins/animation.css" rel="stylesheet">
<link href="{{asset('frontend')}}/css/plugins/bootstrap.min.css" rel="stylesheet">
<link href="{{asset('frontend')}}/css/plugins/flaticon.css" rel="stylesheet">
<link href="{{asset('frontend')}}/css/plugins/font-awesome.css" rel="stylesheet">
<link href="{{asset('frontend')}}/css/plugins/iconfont.css" rel="stylesheet">
<link href="{{asset('frontend')}}/css/plugins/ion.rangeSlider.min.css" rel="stylesheet">
<link href="{{asset('frontend')}}/css/plugins/light-box.css" rel="stylesheet">
<link href="{{asset('frontend')}}/css/plugins/line-icons.css" rel="stylesheet">
<link href="{{asset('frontend')}}/css/plugins/slick-theme.css" rel="stylesheet">
<link href="{{asset('frontend')}}/css/plugins/slick.css" rel="stylesheet">
<link href="{{asset('frontend')}}/css/plugins/snackbar.min.css" rel="stylesheet">
<link href="{{asset('frontend')}}/css/plugins/themify.css" rel="stylesheet">
<link href="{{asset('frontend')}}/css/styles.css" rel="stylesheet">
